# Generated by Django 5.1.15 on 2026-05-08 12:46

import django.db.models.deletion
import hospital_app.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Obat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kode",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        validators=[hospital_app.validators.validate_kode_obat],
                    ),
                ),
                ("nama", models.CharField(max_length=120)),
                ("satuan", models.CharField(default="tablet", max_length=20)),
                ("stok", models.PositiveIntegerField(default=0)),
                (
                    "harga",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
            options={
                "verbose_name": "Obat",
                "verbose_name_plural": "Obat",
                "ordering": ["nama"],
            },
        ),
        migrations.CreateModel(
            name="Apoteker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nip", models.CharField(db_index=True, max_length=20, unique=True)),
                (
                    "nama",
                    models.CharField(
                        max_length=120,
                        validators=[hospital_app.validators.validate_name],
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apoteker_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nama"],
            },
        ),
        migrations.CreateModel(
            name="Dokter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nip", models.CharField(db_index=True, max_length=20, unique=True)),
                (
                    "nama",
                    models.CharField(
                        max_length=120,
                        validators=[hospital_app.validators.validate_name],
                    ),
                ),
                ("spesialisasi", models.CharField(max_length=80)),
                (
                    "no_telepon",
                    models.CharField(
                        max_length=15,
                        validators=[hospital_app.validators.validate_phone],
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dokter_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nama"],
            },
        ),
        migrations.CreateModel(
            name="Pasien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nrm",
                    models.CharField(
                        db_index=True,
                        max_length=16,
                        unique=True,
                        validators=[hospital_app.validators.validate_nrm],
                        verbose_name="Nomor Rekam Medis",
                    ),
                ),
                (
                    "nik",
                    models.CharField(
                        max_length=16,
                        unique=True,
                        validators=[hospital_app.validators.validate_nik],
                        verbose_name="NIK",
                    ),
                ),
                (
                    "nama",
                    models.CharField(
                        max_length=120,
                        validators=[hospital_app.validators.validate_name],
                    ),
                ),
                ("tanggal_lahir", models.DateField()),
                (
                    "jenis_kelamin",
                    models.CharField(
                        choices=[("L", "Laki-laki"), ("P", "Perempuan")], max_length=1
                    ),
                ),
                (
                    "no_telepon",
                    models.CharField(
                        max_length=15,
                        validators=[hospital_app.validators.validate_phone],
                    ),
                ),
                ("alamat", models.TextField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Akun login pasien (opsional - pasien bisa belum punya akun).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pasien_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pasien",
                "verbose_name_plural": "Pasien",
                "ordering": ["nrm"],
            },
        ),
    ]
