# Generated by Django 5.1.15 on 2026-05-08 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RekamMedis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomor", models.CharField(db_index=True, max_length=20, unique=True)),
                ("tanggal", models.DateField()),
                ("anamnesis", models.TextField(blank=True, max_length=1000)),
                ("diagnosa", models.TextField(max_length=500)),
                ("catatan_dokter", models.TextField(blank=True, max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dokter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rekam_medis",
                        to="hospital_app.dokter",
                    ),
                ),
                (
                    "pasien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rekam_medis",
                        to="hospital_app.pasien",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rekam Medis",
                "verbose_name_plural": "Rekam Medis",
                "ordering": ["-tanggal", "-id"],
            },
        ),
    ]
