# Generated by Django 5.1.15 on 2026-05-08 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital_app", "0002_rekammedis"),
    ]

    operations = [
        migrations.CreateModel(
            name="JadwalDokter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hari",
                    models.CharField(
                        choices=[
                            ("SEN", "Senin"),
                            ("SEL", "Selasa"),
                            ("RAB", "Rabu"),
                            ("KAM", "Kamis"),
                            ("JUM", "Jumat"),
                            ("SAB", "Sabtu"),
                            ("MIN", "Minggu"),
                        ],
                        max_length=3,
                    ),
                ),
                ("jam_mulai", models.TimeField()),
                ("jam_selesai", models.TimeField()),
                ("ruangan", models.CharField(max_length=40)),
                (
                    "dokter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jadwal",
                        to="hospital_app.dokter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jadwal Dokter",
                "verbose_name_plural": "Jadwal Dokter",
                "ordering": ["dokter", "hari", "jam_mulai"],
            },
        ),
        migrations.CreateModel(
            name="Resep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomor", models.CharField(db_index=True, max_length=20, unique=True)),
                ("tanggal", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("DIKELUARKAN", "Dikeluarkan oleh Apoteker"),
                            ("DIBATALKAN", "Dibatalkan"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("catatan", models.TextField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "apoteker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resep_set",
                        to="hospital_app.apoteker",
                    ),
                ),
                (
                    "dokter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resep_set",
                        to="hospital_app.dokter",
                    ),
                ),
                (
                    "rekam_medis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resep_set",
                        to="hospital_app.rekammedis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resep",
                "verbose_name_plural": "Resep",
                "ordering": ["-tanggal", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ResepItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jumlah", models.PositiveIntegerField()),
                ("aturan_pakai", models.CharField(max_length=120)),
                (
                    "obat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hospital_app.obat",
                    ),
                ),
                (
                    "resep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="hospital_app.resep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Resep",
                "verbose_name_plural": "Item Resep",
            },
        ),
    ]
